languageCode = "en-us"
title = "Game Manglement"
theme = "robust-custom"
publishDir = "docs"
baseUrl = "https://pumbers.github.io/game-manglement/"

[params]
  description = "Thoughts and stuff for tabletop gaming"
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lato" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.png"
  name = "Paul Umbers"
  description = "Board and tabletop RPG gamer for over 40 years and general mis-manager of my time and effort in writing for RPGs, so here's some thoughts and stuff."
  facebook = "https://www.facebook.com/paul.umbers"
  discord = "https://discordapp.com/users/352505602041315328/"
  github = "https://github.com/pumbers"
  # twitter = "https://twitter.com/JustPaulU?lang=en"
  # mewe = "https://mewe.com/profile/5bbd11ab2ee15f2bb8b1e7f0"
  # google = "https://plus.google.com/u/0/+PaulUmbers"

[outputs]
page = [ "HTML"] # if you want AMP enable.

[markup.goldmark.renderer]
unsafe = true